    version: "3"
    services:
      angular:
        build: .
        ports:
          - "4200:4200"
        depends_on:
            - seleniumhub
        networks:
            front:
                aliases:
                    - angular_service
      seleniumhub:
          image: selenium/standalone-chrome:latest
          ports:
            - 4444
          networks: 
            - front
    networks:
        front:
            driver: bridge
    