    version: "3"
    services:
#      angular:
#        build: .
#        ports:
#          - "4200:4200"
#        networks:
#            - front
      angular:
        image: ruchitgandhi/angular_mean:test
        ports:
          - "4200:4200"
        networks:
            - front
      seleniumhub:
          image: selenium/standalone-chrome-debug:latest
          ports:
            - 4444:4444
            - 5900:5900
          networks: 
            - front
    networks:
        front:
            driver: overlay